In [1]:
from keras.datasets import mnist
from keras import models
from keras import layers
from keras.utils import to_categorical
import numpy as np

train_images = np.load("omok_train5.npy")
train_labels = np.load("omok_answer5.npy")

print(train_images.shape)
print(train_labels.shape)

train_labels_c = to_categorical(train_labels,num_classes=400)
print("train_labels_c",train_labels_c)

model = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(400,)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(400, activation='softmax'))


model.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])


model.fit(train_images, train_labels_c, epochs=30)
model.save('alphao5.h5')

predict_result = model.predict(train_images)
print("predict_result",predict_result)
for r in predict_result:
    ai_answer = np.argmax(r)
    ii = int(ai_answer / 20)
    jj = ai_answer % 20
    print(ai_answer,ii,jj,end=",")
    print()






(24328, 400)
(24328,)
train_labels_c [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Epoch 1/30
761/761 [==============================] - 4s 4ms/step - loss: 4.2035 - accuracy: 0.1502
Epoch 2/30
761/761 [==============================] - 3s 4ms/step - loss: 3.7913 - accuracy: 0.1946
Epoch 3/30
761/761 [==============================] - 3s 4ms/step - loss: 3.6164 - accuracy: 0.2159
Epoch 4/30
761/761 [==============================] - 3s 4ms/step - loss: 3.4379 - accuracy: 0.2401
Epoch 5/30
761/761 [==============================] - 3s 4ms/step - loss: 3.2676 - accuracy: 0.2637
Epoch 6/30
761/761 [==============================] - 3s 4ms/step - loss: 3.1006 - accuracy: 0.2872
Epoch 7/30
761/761 [==============================] - 3s 4ms/step - loss: 2.9466 - accuracy: 0.3107
Epoch 8/30
761/761 [==============================] - 3s 4ms/step - loss: 2.8020 - accuracy: 0.3336
Epoch 9

314 15 14,
294 14 14,
295 14 15,
333 16 13,
238 11 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
335 16 15,
274 13 14,
313 15 13,
234 11 14,
294 14 14,
256 12 16,
292 14 12,
271 13 11,
332 16 12,
351 17 11,
312 15 12,
272 13 12,
312 15 12,
310 15 10,
376 18 16,
355 17 15,
374 18 14,
290 14 10,
291 14 11,
293 14 13,
314 15 14,
354 17 14,
353 17 13,
352 17 12,
372 18 12,
352 17 12,
372 18 12,
396 19 16,
372 18 12,
373 18 13,
377 18 17,
378 18 18,
335 16 15,
398 19 18,
318 15 18,
338 16 18,
318 15 18,
394 19 14,
299 14 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
294 14 14,
293 14 13,
272 13 12,
277 13 17,
295 14 15,
255 12 15,
235 11 15,
273 13 13,
357 17 17,
377 18 17,
335 16 15,
313 15 13,
298 14 18,
295 14 15,
253 12 13,
271 13 11,
292 14 12,
274 13 14,
272 13 12,
236 11 16,
312 15 12,
217 10 17,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,

204 10 4,
222 11 2,
226 11 6,
245 12 5,
226 11 6,
222 11 2,
226 11 6,
346 17 6,
207 10 7,
135 6 15,
208 10 8,
135 6 15,
208 10 8,
229 11 9,
228 11 8,
229 11 9,
208 10 8,
189 9 9,
207 10 7,
187 9 7,
326 16 6,
346 17 6,
243 12 3,
144 7 4,
168 8 8,
187 9 7,
168 8 8,
334 16 14,
168 8 8,
187 9 7,
168 8 8,
191 9 11,
248 12 8,
191 9 11,
168 8 8,
191 9 11,
168 8 8,
191 9 11,
168 8 8,
191 9 11,
190 9 10,
191 9 11,
190 9 10,
191 9 11,
190 9 10,
191 9 11,
190 9 10,
229 11 9,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
316 15 16,
318 15 18,
334 16 14,
314 15 14,
293 14 13,
253 12 13,
334 16 14,
312 15 12,
296 14 16,
277 13 17,
313 15 13,
273 13 13,
353 17 13,
372 18 12,
354 17 14,
355 17 15,
290 14 10,
291 14 11,
270 13 10,
310 15 10,
270 13 10,
271 13 11,
234 11 14,
214 10 14,
269 13 9,
294 14 14,
269 13 9,
332 16 12,
289 14 9,
309 15 9,
327 16 7,
309 15 9,
327 16 7,
346 17 6,
337 16 17,
358 17 18,
337 16 17,
231 11 11,
211 10 11,
252 12 12,
210 10 10,
233 11 13,
195 9 15,
2

292 14 12,
213 10 13,
175 8 15,
251 12 11,
231 11 11,
251 12 11,
270 13 10,
253 12 13,
270 13 10,
273 13 13,
193 9 13,
293 14 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
334 16 14,
235 11 15,
296 14 16,
255 12 15,
253 12 13,
235 11 15,
214 10 14,
295 14 15,
335 16 15,
356 17 16,
335 16 15,
354 17 14,
278 13 18,
259 12 19,
338 16 18,
258 12 18,
337 16 17,
257 12 17,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
253 12 13,
297 14 17,
335 16 15,
335 16 15,
354 17 14,
375 18 15,
355 17 15,
273 13 13,
235 11 15,
253 12 13,
252 12 12,
293 14 13,
233 11 13,
292 14 12,
291 14 11,
333 16 13,
296 14 16,
333 16 13,
313 15 13,
331 16 11,
332 16 12,
331 16 11,
232 11 12,
312 15 12,
255 12 15,
350 17 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
334 16 14,
257 12 17,
237 11 17,
337 16 17,
297 14 17,
256 12 16,
255 12 15,
235 11 15,
214 10 14,
318 15 18,
319 15 19,
273 13 13,
216 10 16,
356 17 16,
3

390 19 10,
375 18 15,
377 18 17,
397 19 17,
292 14 12,
293 14 13,
375 18 15,
374 18 14,
394 19 14,
312 15 12,
291 14 11,
372 18 12,
373 18 13,
332 16 12,
392 19 12,
331 16 11,
330 16 10,
350 17 10,
274 13 14,
369 18 9,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
356 17 16,
335 16 15,
255 12 15,
253 12 13,
274 13 14,
297 14 17,
354 17 14,
278 13 18,
337 16 17,
298 14 18,
258 12 18,
257 12 17,
295 14 15,
236 11 16,
234 11 14,
215 10 15,
259 12 19,
215 10 15,
194 9 14,
299 14 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
356 17 16,
256 12 16,
375 18 15,
354 17 14,
356 17 16,
376 18 16,
274 13 14,
337 16 17,
273 13 13,
272 13 12,
256 12 16,
313 15 13,
277 13 17,
276 13 16,
237 11 17,
218 10 18,
235 11 15,
298 14 18,
236 11 16,
238 11 18,
233 11 13,
234 11 14,
193 9 13,
214 10 14,
295 14 15,
213 10 13,
295 14 15,
232 11 12,
295 14 15,
215 10 15,
217 10 17,
293 14 13,
198 9 18,
315 15 15,
336

292 14 12,
271 13 11,
311 15 11,
211 10 11,
231 11 11,
190 9 10,
356 17 16,
190 9 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
335 16 15,
354 17 14,
356 17 16,
376 18 16,
314 15 14,
293 14 13,
313 15 13,
256 12 16,
377 18 17,
259 12 19,
338 16 18,
375 18 15,
377 18 17,
398 19 18,
312 15 12,
311 15 11,
298 14 18,
258 12 18,
353 17 13,
271 13 11,
291 14 11,
252 12 12,
270 13 10,
249 12 9,
289 14 9,
273 13 13,
292 14 12,
214 10 14,
270 13 10,
288 14 8,
358 17 18,
318 15 18,
251 12 11,
231 11 11,
294 14 14,
233 11 13,
195 9 15,
232 11 12,
230 11 10,
234 11 14,
235 11 15,
194 9 14,
230 11 10,
174 8 14,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
335 16 15,
354 17 14,
356 17 16,
376 18 16,
314 15 14,
293 14 13,
313 15 13,
256 12 16,
331 16 11,
292 14 12,
333 16 13,
292 14 12,
294 14 14,
256 12 16,
312 15 12,
311 15 11,
273 13 13,
290 14 

336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
356 17 16,
294 14 14,
375 18 15,
294 14 14,
356 17 16,
295 14 15,
238 11 18,
376 18 16,
333 16 13,
293 14 13,
294 14 14,
334 16 14,
337 16 17,
318 15 18,
332 16 12,
351 17 11,
331 16 11,
330 16 10,
353 17 13,
393 19 13,
354 17 14,
258 12 18,
239 11 19,
257 12 17,
255 12 15,
297 14 17,
237 11 17,
298 14 18,
299 14 19,
278 13 18,
238 11 18,
338 16 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
376 18 16,
335 16 15,
337 16 17,
294 14 14,
293 14 13,
255 12 15,
235 11 15,
337 16 17,
273 13 13,
358 17 18,
379 18 19,
216 10 16,
313 15 13,
333 16 13,
233 11 13,
253 12 13,
214 10 14,
232 11 12,
335 16 15,
232 11 12,
214 10 14,
194 9 14,
271 13 11,
290 14 10,
272 13 12,
270 13 10,
251 12 11,
314 15 14,
311 15 11,
314 15 14,
311 15 11,
231 11 11,
331 16 11,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
296 14 16,
277 13 17,


270 13 10,
332 16 12,
252 12 12,
232 11 12,
290 14 10,
289 14 9,
271 13 11,
269 13 9,
309 15 9,
233 11 13,
328 16 8,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
274 13 14,
335 16 15,
334 16 14,
294 14 14,
313 15 13,
278 13 18,
297 14 17,
373 18 13,
289 14 9,
356 17 16,
292 14 12,
376 18 16,
396 19 16,
354 17 14,
392 19 12,
355 17 15,
353 17 13,
372 18 12,
311 15 11,
374 18 14,
375 18 15,
276 13 16,
279 13 19,
371 18 11,
370 18 10,
358 17 18,
357 17 17,
235 11 15,
268 13 8,
290 14 10,
271 13 11,
250 12 10,
331 16 11,
351 17 11,
268 13 8,
312 15 12,
247 12 7,
352 17 12,
247 12 7,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
274 13 14,
335 16 15,
334 16 14,
314 15 14,
293 14 13,
297 14 17,
278 13 18,
333 16 13,
334 16 14,
292 14 12,
334 16 14,
354 17 14,
373 18 13,
312 15 12,
375 18 15,
352 17 12,
353 17 13,
372 18 12,
332 16 12,
396 19 16,
375 18 15,
311 15 11,
253 12 13,
310 15 10,
313 15 13,
356 17 1

297 14 17,
318 15 18,
311 15 11,
314 15 14,
309 15 9,
310 15 10,
332 16 12,
376 18 16,
331 16 11,
353 17 13,
332 16 12,
352 17 12,
331 16 11,
330 16 10,
335 16 15,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
335 16 15,
295 14 15,
358 17 18,
335 16 15,
253 12 13,
335 16 15,
334 16 14,
339 16 19,
338 16 18,
297 14 17,
278 13 18,
354 17 14,
373 18 13,
298 14 18,
296 14 16,
353 17 13,
216 10 16,
256 12 16,
258 12 18,
277 13 17,
235 11 15,
273 13 13,
237 11 17,
195 9 15,
197 9 17,
178 8 18,
238 11 18,
272 13 12,
271 13 11,
236 11 16,
215 10 15,
177 8 17,
218 10 18,
236 11 16,
215 10 15,
214 10 14,
176 8 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
235 11 15,
274 13 14,
273 13 13,
292 14 12,
293 14 13,
276 13 16,
335 16 15,
314 15 14,
295 14 15,
256 12 16,
296 14 16,
313 15 13,
294 14 14,
297 14 17,
234 11 14,
277 13 17,
278 13 18,
355 17 15,
339 16 19,
355 17 15,
216 10 16,
197 9 17,
271 13 11,
334 16

310 15 10,
330 16 10,
216 10 16,
273 13 13,
237 11 17,
258 12 18,
257 12 17,
256 12 16,
236 11 16,
256 12 16,
294 14 14,
234 11 14,
194 9 14,
358 17 18,
194 9 14,
215 10 15,
196 9 16,
178 8 18,
196 9 16,
193 9 13,
156 7 16,
176 8 16,
175 8 15,
292 14 12,
349 17 9,
373 18 13,
194 9 14,
177 8 17,
175 8 15,
177 8 17,
154 7 14,
238 11 18,
133 6 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
356 17 16,
294 14 14,
376 18 16,
274 13 14,
234 11 14,
255 12 15,
293 14 13,
273 13 13,
252 12 12,
257 12 17,
256 12 16,
236 11 16,
215 10 15,
196 9 16,
198 9 18,
216 10 16,
292 14 12,
237 11 17,
277 13 17,
174 8 14,
335 16 15,
197 9 17,
335 16 15,
176 8 16,
277 13 17,
195 9 15,
335 16 15,
175 8 15,
173 8 13,
178 8 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
276 13 16,
256 12 16,
277 13 17,
274 13 14,
234 11 14,
235 11 15,
253 12 13,
253 12 13,
255 12 15,
216 10 16,
273 13 13,
295 14 15,
356 17 16,
296 14 16,
29

335 16 15,
313 15 13,
255 12 15,
234 11 14,
235 11 15,
215 10 15,
236 11 16,
234 11 14,
214 10 14,
253 12 13,
196 9 16,
232 11 12,
211 10 11,
272 13 12,
291 14 11,
252 12 12,
292 14 12,
293 14 13,
250 12 10,
293 14 13,
230 11 10,
335 16 15,
314 15 14,
270 13 10,
213 10 13,
252 12 12,
271 13 11,
313 15 13,
233 11 13,
333 16 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
274 13 14,
274 13 14,
276 13 16,
295 14 15,
253 12 13,
337 16 17,
358 17 18,
335 16 15,
334 16 14,
338 16 18,
339 16 19,
297 14 17,
272 13 12,
353 17 13,
278 13 18,
259 12 19,
278 13 18,
374 18 14,
273 13 13,
252 12 12,
313 15 13,
314 15 14,
235 11 15,
355 17 15,
235 11 15,
314 15 14,
235 11 15,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
274 13 14,
335 16 15,
313 15 13,
256 12 16,
237 11 17,
332 16 12,
313 15 13,
273 13 13,
236 11 16,
234 11 14,
238 11 18,
239 11 19,
217 10 17,
335 16 15,
175 8 15,
196 9 16,
197 9 17,
177 8 17,
216 

236 11 16,
196 9 16,
258 12 18,
257 12 17,
238 11 18,
278 13 18,
237 11 17,
234 11 14,
239 11 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
253 12 13,
297 14 17,
297 14 17,
318 15 18,
319 15 19,
375 18 15,
355 17 15,
295 14 15,
337 16 17,
354 17 14,
312 15 12,
332 16 12,
311 15 11,
373 18 13,
392 19 12,
313 15 13,
372 18 12,
333 16 13,
353 17 13,
331 16 11,
334 16 14,
370 18 10,
329 16 9,
370 18 10,
351 17 11,
310 15 10,
350 17 10,
352 17 12,
289 14 9,
394 19 14,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
334 16 14,
235 11 15,
214 10 14,
216 10 16,
273 13 13,
197 9 17,
178 8 18,
258 12 18,
296 14 16,
237 11 17,
195 9 15,
257 12 17,
217 10 17,
256 12 16,
255 12 15,
236 11 16,
234 11 14,
196 9 16,
276 13 16,
176 8 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
334 16 14,
235 11 15,
296 14 16,
255 12 15,
235 11 15,
255 12 15,
253 12 13,
316 15 16,
318 15 18,
257 12 17,
258 12 18,
236 11 

254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
335 16 15,
295 14 15,
335 16 15,
314 15 14,
335 16 15,
338 16 18,
276 13 16,
297 14 17,
313 15 13,
256 12 16,
292 14 12,
271 13 11,
257 12 17,
274 13 14,
298 14 18,
332 16 12,
376 18 16,
355 17 15,
356 17 16,
396 19 16,
375 18 15,
318 15 18,
373 18 13,
372 18 12,
352 17 12,
331 16 11,
330 16 10,
311 15 11,
354 17 14,
392 19 12,
331 16 11,
329 16 9,
377 18 17,
378 18 18,
377 18 17,
378 18 18,
353 17 13,
312 15 12,
293 14 13,
312 15 12,
331 16 11,
329 16 9,
272 13 12,
329 16 9,
331 16 11,
252 12 12,
290 14 10,
252 12 12,
290 14 10,
253 12 13,
290 14 10,
253 12 13,
232 11 12,
209 10 9,
269 13 9,
210 10 10,
230 11 10,
189 9 9,
210 10 10,
233 11 13,
230 11 10,
233 11 13,
230 11 10,
228 11 8,
247 12 7,
190 9 10,
247 12 7,
188 9 8,
191 9 11,
357 17 17,
228 11 8,
214 10 14,
195 9 15,
214 10 14,
232 11 12,
357 17 17,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
297 14 17,
277 

354 17 14,
297 14 17,
313 15 13,
255 12 15,
234 11 14,
273 13 13,
337 16 17,
273 13 13,
272 13 12,
278 13 18,
259 12 19,
215 10 15,
258 12 18,
239 11 19,
195 9 15,
273 13 13,
194 9 14,
214 10 14,
217 10 17,
299 14 19,
257 12 17,
237 11 17,
212 10 12,
193 9 13,
172 8 12,
252 12 12,
232 11 12,
252 12 12,
233 11 13,
356 17 16,
238 11 18,
256 12 16,
218 10 18,
175 8 15,
210 10 10,
339 16 19,
318 15 18,
175 8 15,
318 15 18,
191 9 11,
318 15 18,
314 15 14,
210 10 10,
209 10 9,
190 9 10,
169 8 9,
230 11 10,
274 13 14,
170 8 10,
150 7 10,
170 8 10,
150 7 10,
170 8 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
334 16 14,
335 16 15,
294 14 14,
354 17 14,
297 14 17,
295 14 15,
295 14 15,
296 14 16,
236 11 16,
235 11 15,
214 10 14,
355 17 15,
375 18 15,
356 17 16,
353 17 13,
298 14 18,
319 15 19,
258 12 18,
255 12 15,
216 10 16,
197 9 17,
195 9 15,
174 8 14,
198 9 18,
238 11 18,
379 18 19,
277 13 17,
279 13 19,
237 11 17,
219 10 19,
259 12 19,
154 7 14,
175 8 15,

294 14 14,
256 12 16,
333 16 13,
293 14 13,
376 18 16,
356 17 16,
355 17 15,
397 19 17,
314 15 14,
374 18 14,
312 15 12,
371 18 11,
312 15 12,
351 17 11,
312 15 12,
311 15 11,
331 16 11,
373 18 13,
332 16 12,
330 16 10,
372 18 12,
268 13 8,
332 16 12,
270 13 10,
255 12 15,
268 13 8,
329 16 9,
289 14 9,
329 16 9,
195 9 15,
234 11 14,
195 9 15,
236 11 16,
195 9 15,
193 9 13,
195 9 15,
193 9 13,
289 14 9,
213 10 13,
210 10 10,
298 14 18,
197 9 17,
178 8 18,
210 10 10,
252 12 12,
210 10 10,
237 11 17,
308 15 8,
369 18 9,
308 15 8,
388 19 8,
354 17 14,
232 11 12,
354 17 14,
192 9 12,
230 11 10,
251 12 11,
230 11 10,
191 9 11,
230 11 10,
290 14 10,
251 12 11,
272 13 12,
251 12 11,
232 11 12,
252 12 12,
175 8 15,
194 9 14,
249 12 9,
366 18 6,
249 12 9,
190 9 10,
191 9 11,
190 9 10,
275 13 15,
150 7 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
314 15 14,
272 13 12,
313 15 13,
273 13 13,
332 16 12,
294 14 14,
353 17

277 13 17,
256 12 16,
255 12 15,
215 10 15,
274 13 14,
276 13 16,
236 11 16,
293 14 13,
291 14 11,
295 14 15,
271 13 11,
333 16 13,
314 15 14,
272 13 12,
311 15 11,
251 12 11,
313 15 13,
351 17 11,
290 14 10,
312 15 12,
354 17 14,
294 14 14,
296 14 16,
252 12 12,
292 14 12,
250 12 10,
273 13 13,
250 12 10,
273 13 13,
248 12 8,
269 13 9,
228 11 8,
269 13 9,
228 11 8,
269 13 9,
355 17 15,
217 10 17,
198 9 18,
330 16 10,
349 17 9,
374 18 14,
394 19 14,
374 18 14,
373 18 13,
353 17 13,
331 16 11,
332 16 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
294 14 14,
277 13 17,
377 18 17,
357 17 17,
294 14 14,
295 14 15,
276 13 16,
234 11 14,
255 12 15,
253 12 13,
356 17 16,
318 15 18,
272 13 12,
312 15 12,
331 16 11,
313 15 13,
293 14 13,
291 14 11,
335 16 15,
314 15 14,
355 17 15,
271 13 11,
355 17 15,
311 15 11,
310 15 10,
231 11 11,
251 12 11,
232 11 12,
274 13 14,
233 11 13,
230 11 10,
235 11 15,
315 15 15,
336 16 16,
317 15 

298 14 18,
216 10 16,
257 12 17,
273 13 13,
292 14 12,
216 10 16,
197 9 17,
252 12 12,
231 11 11,
216 10 16,
239 11 19,
195 9 15,
217 10 17,
214 10 14,
233 11 13,
232 11 12,
217 10 17,
177 8 17,
192 9 12,
213 10 13,
212 10 12,
194 9 14,
212 10 12,
194 9 14,
155 7 15,
194 9 14,
176 8 16,
156 7 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
296 14 16,
277 13 17,
274 13 14,
314 15 14,
293 14 13,
297 14 17,
278 13 18,
333 16 13,
295 14 15,
255 12 15,
234 11 14,
294 14 14,
313 15 13,
313 15 13,
214 10 14,
194 9 14,
195 9 15,
233 11 13,
339 16 19,
272 13 12,
195 9 15,
233 11 13,
292 14 12,
271 13 11,
292 14 12,
372 18 12,
310 15 10,
272 13 12,
273 13 13,
233 11 13,
290 14 10,
311 15 11,
289 14 9,
293 14 13,
331 16 11,
231 11 11,
268 13 8,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
356 17 16,
294 14 14,
295 14 15,
274 13 14,
234 11 14,
255 12 15,
257 12 17,
276 13 16,
215 10 15,
235 11 15,
216

317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
295 14 15,
253 12 13,
356 17 16,
255 12 15,
356 17 16,
272 13 12,
356 17 16,
376 18 16,
255 12 15,
236 11 16,
335 16 15,
377 18 17,
337 16 17,
298 14 18,
375 18 15,
318 15 18,
331 16 11,
235 11 15,
331 16 11,
312 15 12,
311 15 11,
351 17 11,
278 13 18,
259 12 19,
278 13 18,
358 17 18,
338 16 18,
339 16 19,
251 12 11,
271 13 11,
292 14 12,
216 10 16,
290 14 10,
289 14 9,
273 13 13,
277 13 17,
196 9 16,
277 13 17,
214 10 14,
319 15 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
356 17 16,
277 13 17,
274 13 14,
253 12 13,
255 12 15,
235 11 15,
273 13 13,
272 13 12,
236 11 16,
293 14 13,
314 15 14,
277 13 17,
214 10 14,
194 9 14,
310 15 10,
194 9 14,
217 10 17,
198 9 18,
352 17 12,
358 17 18,
352 17 12,
333 16 13,
354 17 14,
294 14 14,
353 17 13,
355 17 15,
311 15 11,
290 14 10,
292 14 12,
371 18 11,
331 16 11,
371 18 11,
395 19 15,
374 

236 11 16,
337 16 17,
357 17 17,
238 11 18,
238 11 18,
351 17 11,
233 11 13,
375 18 15,
196 9 16,
352 17 12,
333 16 13,
353 17 13,
354 17 14,
331 16 11,
350 17 10,
311 15 11,
291 14 11,
290 14 10,
332 16 12,
290 14 10,
332 16 12,
371 18 11,
394 19 14,
371 18 11,
391 19 11,
372 18 12,
250 12 10,
271 13 11,
217 10 17,
198 9 18,
370 18 10,
309 15 9,
308 15 8,
393 19 13,
288 14 8,
393 19 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
337 16 17,
294 14 14,
293 14 13,
255 12 15,
235 11 15,
273 13 13,
216 10 16,
335 16 15,
256 12 16,
236 11 16,
215 10 15,
193 9 13,
215 10 15,
213 10 13,
197 9 17,
178 8 18,
217 10 17,
194 9 14,
217 10 17,
257 12 17,
237 11 17,
257 12 17,
177 8 17,
157 7 17,
196 9 16,
253 12 13,
196 9 16,
253 12 13,
158 7 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
297 14 17,
274 13 14,
354 17 14,
253 12 13,
356 17 16,
396 19 16,
235 11 15,
274 13 14,
277 13 17,
25